<a href="https://colab.research.google.com/github/K-107/dki/blob/main/Food_Detection/%EB%A9%80%ED%8B%B0%EC%9D%B4%EB%AF%B8%EC%A7%80_%EA%B0%9C%EC%88%98_%EC%84%B8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import os
import re
import unicodedata

# import unicodedata # ㄲㅐㅈㅣㄴㄱㅓㅅ ㅂㅜㅌㅇㅣㄱㅣ

In [40]:
path = '/content/drive/MyDrive/음식인식/multi/'

p = re.compile('[가-힣]*')

box = []
for name in os.listdir(path):
  name = unicodedata.normalize('NFC',name)
  m = p.findall(name)
  for item in m:
    if item:
      box.append(item)

box

['김치전',
 '파전',
 '깻잎전',
 '고추튀김',
 '돼지고기',
 '수육',
 '배추김치',
 '깻잎전',
 '동그랑땡',
 '돼지고기',
 '수육',
 '열무김치',
 '물냉면',
 '꽈리고추찜',
 '가지나물',
 '간장게장',
 '양념게장',
 '계란후라이',
 '낙지볶음',
 '부추전',
 '무생채',
 '귀리밥',
 '두부양념조림',
 '녹두전',
 '딸기',
 '김치',
 '단무지',
 '갈치구이',
 '배추김치',
 '귤',
 '문어',
 '꽈리고추찜',
 '흑미밥',
 '돼지고기',
 '수육',
 '갓김치',
 '단무지무침',
 '시금치나물',
 '소시지야채볶음',
 '돼지고기',
 '수육',
 '배추김치',
 '굴전',
 '방울토마토',
 '브로콜리',
 '녹두전',
 '김치전',
 '가지전',
 '호박전',
 '단무지',
 '깍두기',
 '귤',
 '금귤',
 '딸기',
 '귤',
 '단무지',
 '김밥',
 '낙지볶음',
 '미역냉국',
 '귀리밥',
 '김',
 '귀리밥',
 '오징어볶음',
 '매생이국',
 '가자미구이',
 '김',
 '현미밥',
 '가지냉국',
 '미역냉국',
 '김치볶음',
 '계란말이',
 '돼지고기',
 '수육',
 '배추김치',
 '단팥죽',
 '나박김치',
 '단팥죽',
 '백김치',
 '갈치구이',
 '계란말이',
 '김치찌개',
 '흑미밥',
 '금귤',
 '오렌지',
 '오렌지',
 '단무지',
 '김밥',
 '귀리밥',
 '무생채',
 '생선구이',
 '들깻잎',
 '미역국',
 '난자완스',
 '짜장면',
 '돼지고기',
 '수육',
 '배추김치',
 '꼬막찜',
 '굴전',
 '미역국',
 '배추김치',
 '가자미구이',
 '마늘장아찌',
 '단팥죽',
 '호박죽',
 '대하구이',
 '조개구이',
 '마늘',
 '조개국',
 '오이',
 '깻잎찜',
 '감자조림',
 '대구지리',
 '흑미밥',
 '가지냉국',
 '미역냉국',
 '단무지무침',
 '오이초절임',
 '녹두전',
 '부추전',
 '장아찌',
 '깻잎나물',
 '깻잎조림',
 '깻잎찜',
 '난자완스',
 '짜장면',
 '깻잎전',
 '고추튀김',
 '굴전',
 '낙지볶음',
 '콩나물무침',
 '조개탕',
 '가지전',
 '호박전',
 '떡볶이',
 '김밥',
 '짜장면',
 '짬뽕',
 '탕수육',
 '물냉면',
 '비빔냉면',
 '전',
 '탕수육',
 '짜장면',
 '짬뽕',
 '양파',
 '단무지',
 '짜장면',
 '짬뽕',
 '짜장면',
 '짬뽕',
 '배추김치',
 '떡볶이',
 '순대',
 '짜장면',
 '짬뽕',
 '탕수육',
 '탕수육',
 '짜장면',
 '짬뽕',
 '짜장면',
 '탕수육',
 '짬뽕',
 '짜장면',
 '짬뽕',
 '짜장면',
 '탕수육',
 '단무지',
 '샌드위치',
 '샌드위치',
 '샌드위치',
 '과일샐러드',
 '배추김치',
 '백김치',
 '물냉면',
 '물냉면',
 '부추전',
 '후라이드치킨',
 '양념치킨',
 '방울토마토',
 '레몬',
 '라면',
 '단무지',
 '김밥',
 '밥',
 '소고기무국',
 '딸기',
 '포도',
 '귤',
 '짜장면',
 '짜장면',
 '짜장면',
 '짬뽕',
 '탕수육',
 '단무지',
 '콜라',
 '짜장면',
 '짬뽕',
 '탕수육',
 '배추김치',
 '짜장면',
 '짜장면',
 '짬뽕',
 '탕수육',
 '매생이국',
 '현미밥',
 '짬뽕',
 '단무지',
 '단무지',
 '짜장면',
 '탕수육',
 '양파',
 '양파',
 '군만두',
 '라면',
 '김밥',
 '후라이드치킨',
 '양념치킨',
 '라면',
 '김밥',
 '배추김치',
 '짜장면',
 '짬뽕',
 '단무지',
 '짜장면',
 '짬뽕',
 '탕수육',
 '배추김치',
 '딸기',
 '귤',
 '잡곡밥',
 '미역국',
 '햄구이',
 '나물',
 '부침',
 '라면',
 '단무지',
 '식빵',
 '열무김치국수',
 '오이냉국',
 '가지볶음',
 '육회',
 '비빔냉면',
 '짬뽕',
 '짜장면',
 '단무지',
 '양파',
 '탕수육',
 '칼국수',
 '파전',
 '배추김치',
 '물냉면',
 '비빔냉면',
 '식빵',
 '과일샐러드',
 '배추김치',
 '백김치',
 '밥',
 '김',
 '찌개',
 '잔치국수',
 '비빔국수',
 '콩나물무침',
 '배추김치',
 '육회',
 '빈대떡',
 '김밥',
 '양파장아찌',
 '짜장면',
 '짬뽕',
 '탕수육',
 '파전',
 '잔치국수',
 '배추김치',
 '총각김치',
 '짜장면',
 '짜장면',
 '탕수육',
 '탕수육',
 '짬뽕',
 '라면',
 '김밥',
 '라면',
 '김밥',
 '잔치국수',
 '만두',
 '식빵',
 '스프',
 '물냉면',
 '비빔냉면',
 '고추장',
 '떡볶이',
 '잡채',
 '배추김치',
 '총각김치',
 '쫄면',
 '김밥',
 '양념치킨',
 '후라이드치킨']

In [41]:
len(box)

299

In [42]:
import pandas as pd
import numpy as np

In [114]:
df = pd.read_excel('/content/drive/MyDrive/음식인식/조리식품 학습중인 데이터 .xlsx', sheet_name=1)
df.head()

   Unnamed: 0 FOOD_NM  index     FOOD_CD  ... 300 장 여부  대중음식여부  test건수  multi 건수
0           1   가리비구이    0.0  N081000001  ...        1       Y     2.0       NaN
1           2   가자미구이    1.0  G013000001  ...        1       Y     NaN       NaN
2           3   가자미조림    2.0  N111000003  ...        1       Y     NaN       NaN
3           4    가자미찜  581.0  N071000002  ...        0       Y     NaN       NaN
4           5    가지나물    3.0  N133000001  ...        1       Y     NaN       NaN

[5 rows x 13 columns]

In [116]:
df['multi 건수'] = 0

In [117]:
df.head()

   Unnamed: 0 FOOD_NM  index     FOOD_CD  ... 300 장 여부  대중음식여부  test건수  multi 건수
0           1   가리비구이    0.0  N081000001  ...        1       Y     2.0         0
1           2   가자미구이    1.0  G013000001  ...        1       Y     NaN         0
2           3   가자미조림    2.0  N111000003  ...        1       Y     NaN         0
3           4    가자미찜  581.0  N071000002  ...        0       Y     NaN         0
4           5    가지나물    3.0  N133000001  ...        1       Y     NaN         0

[5 rows x 13 columns]

In [118]:
exception = []

for box_name in box:
  # print(f'{box_name}')
  # print(df.loc[df.FOOD_NM==f'{box_name}','multi 건수'])
  if box_name in list(df['FOOD_NM']):
    df.loc[df.FOOD_NM==f'{box_name}','multi 건수'] += 1
  else:
    exception.append(box_name)

In [119]:
df.head()

   Unnamed: 0 FOOD_NM  index     FOOD_CD  ... 300 장 여부  대중음식여부  test건수  multi 건수
0           1   가리비구이    0.0  N081000001  ...        1       Y     2.0         0
1           2   가자미구이    1.0  G013000001  ...        1       Y     NaN         2
2           3   가자미조림    2.0  N111000003  ...        1       Y     NaN         0
3           4    가자미찜  581.0  N071000002  ...        0       Y     NaN         0
4           5    가지나물    3.0  N133000001  ...        1       Y     NaN         1

[5 rows x 13 columns]

In [127]:
df.to_excel('/content/drive/MyDrive/음식인식/multi.xlsx')

In [120]:
exception

['돼지고기',
 '수육',
 '돼지고기',
 '수육',
 '김치',
 '돼지고기',
 '수육',
 '돼지고기',
 '수육',
 '돼지고기',
 '수육',
 '돼지고기',
 '수육',
 '전',
 '밥',
 '소고기무국',
 '콜라',
 '군만두',
 '나물',
 '열무김치국수',
 '밥',
 '찌개',
 '비빔국수',
 '빈대떡',
 '양파장아찌',
 '고추장']

In [132]:
# 'FOOD_NM 확정' 이름으로 비교

df_name = pd.read_excel('/content/drive/MyDrive/음식인식/조리식품 학습중인 데이터 .xlsx', sheet_name=0)
fix_name = list(df_name['FOOD_NM 확정'])

In [134]:
for box_name in box:
  if box_name not in fix_name:
    print(box_name)

돼지고기
수육
돼지고기
수육
김치
돼지고기
수육
돼지고기
수육
돼지고기
수육
돼지고기
수육
전
밥
소고기무국
나물
열무김치국수
밥
찌개
비빔국수
빈대떡

# 아래와 같이 하면 에러 뜬다!

In [63]:
df['multi 건수'][0]=2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [69]:
df[df.FOOD_NM=='가리비구이']['multi 건수'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

# loc로 해라!!

In [75]:
df.loc[df.FOOD_NM=='가리비구이','multi 건수'] = 1